# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-18 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190918_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GUser',
            new_name='User',
        ),
    ]
