# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('path_search', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cnum', models.CharField(max_length=30)),
            ],
        ),
    ]
